### ISSUE TITLE
Flux is a very confusing name for this functionality 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_dpd#1]
In particular as we recently integrate the http://flux-framework.org/ as part of the `pysqa` queuing system adapter and currently work on a project of making the flux framework the primary workflow schedule for exascale workflows. More details are available in the recent pyiron Exascale presentation https://youtu.be/lXY5wOYcqxk

**Comment by pmrv** [comment]
I'll need this repostory for SFB related activities, but can rename it once I have time.  It is entirely unrelated to the queuing system.

**Comment by jan-janssen** [comment]
Ok, I changed the visibility of the repository to private until we have a different name for it to minimise the confusion.

**Comment by pmrv** [comment]
I've changed the name, please change it back public visibility (I can't seem to do it).  I will need this repository available under this exact name, because tomorrow a poster will be printed (again) that references this.

**Comment by jan-janssen** [comment]
Done

**Comment by pmrv** [comment]
Thanks!
